variables:
  AWS_REGION: eu-central-1
  STAGE: production

stages:
  - linting
  - deploy

default:
  image: node:18.11

  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules/

install:
  stage: .pre
  script:
    - npm ci --cache .npm --prefer-offline

lint-job:
  stage: linting
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  script:
    - npm run check-lint
    - npm run validate

production-deploy-job:
  resource_group: production
  stage: deploy
  only:
    - main
  except:
    changes:
      - README.md
  script:
    - echo "Deploy"
    - npx sls create_domain --stage $STAGE --verbose
    - npx serverless deploy --region $AWS_REGION --stage $STAGE
