name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.11
        uses: actions/setup-node@v1
        with:
          node-version: 18.11
      - name: Install dependencies
        run: |
          npm install --ignore-scripts
      - name: Run Linting
        run: |
          npm run check-lint
          npm run validate

  deploy:
    environment: production
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.11
        uses: actions/setup-node@v1
        with:
          node-version: 18.11
      - name: Install dependencies
        run: |
          npm install --ignore-scripts
      - name: Deploy to production
        env:
          AWS_REGION: eu-central-1
          STAGE: production
          MOCKINGBIRD_DOMAIN: ${{vars.MOCKINGBIRD_DOMAIN}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          SERVERLESS_ACCESS_KEY: ${{secrets.SERVERLESS_ACCESS_KEY}}
        run: |
          echo "Deploy"
          npx serverless deploy --region $AWS_REGION --stage $STAGE
        # npx sls create_domain --stage $STAGE --verbose
